<h1>Bug</h1>

<?php


$form = $this->form;
$form->setAttribute('action', $this->url('bug'));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;

// bug fieldset
echo "<fieldset class='bug'><legend>Bug</legend>" . PHP_EOL;
$bug = $form->get('bug');
echo $this->formRow($bug->get('title')) . PHP_EOL;
echo $this->formRow($bug->get('description')) . PHP_EOL;
echo "</fieldset>" . PHP_EOL;

// reporter fieldset
$reporter = $bug->get('reporter');
echo "<fieldset class='reporter'><legend>Reporter</legend>" . PHP_EOL;
echo $this->formRow($reporter->get('name')) . PHP_EOL;
echo $this->formRow($reporter->get('email')) . PHP_EOL;
echo "</fieldset>" . PHP_EOL;

// submit button & CSRF element
echo "<div class='submit'>" . PHP_EOL;
//echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit')) . PHP_EOL;
echo "</div>" . PHP_EOL;

echo $this->form()->closeTag($form) . PHP_EOL;


// Option 2
// $form = $this->form;
// $form->setAttribute('action', $this->url('retrieve-password'));
// echo $this->renderForm($form);
