<h1>Retrieve password</h1>

<?php
// option 1
/*
$form = $this->form;
$form->setAttribute('action', $this->url('retrieve-password'));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formLabel($form->get('email')) . PHP_EOL;
echo $this->formInput($form->get('email')) . PHP_EOL;
echo $this->FormElementErrors($form->get('email')) . PHP_EOL;
echo $this->formSubmit($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
*/

// Option 2
/*
$form = $this->form;
$form->setAttribute('action', $this->url('retrieve-password'));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('email')) . PHP_EOL;
echo $this->formRow($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
*/

// Option 3
$form = $this->form;
$form->setAttribute('action', $this->url('retrieve-password'));
echo $this->renderForm($form);
